#ifndef _OBPM_DATALIB_H_
#define _OBPM_DATALIB_H_
extern void obpm_init(void);
extern void obpm_section_size(int);
extern void obpm_material_size(int);
extern void obpm_geometry_size(int);
extern void obpm_feed_size(int);
extern void obpm_load_size(int);
extern void obpm_point_size(int);
extern void obpm_far1d_size(int);
extern void obpm_near1d_size(int);
extern void obpm_near2d_size(int);
extern void obpm_title(const char []);
extern void obpm_xsection1(double);
extern void obpm_ysection1(double);
extern void obpm_zsection1(double);
extern void obpm_xdivision1(int);
extern void obpm_ydivision1(int);
extern void obpm_zdivision1(int);
extern void obpm_xsection(int, ...);
extern void obpm_ysection(int, ...);
extern void obpm_zsection(int, ...);
extern void obpm_xdivision(int, ...);
extern void obpm_ydivision(int, ...);
extern void obpm_zdivision(int, ...);
extern void obpm_material(double, double, double, double, const char []);
extern void obpm_material_dispersion(double, double, double, double, const char []);
extern void obpm_geometry(int, int, double, double, double, double, double, double);
extern void obpm_geometry_array(int, int, const double []);
extern void obpm_geometry_name(const char []);
extern void obpm_feed(char, double, double, double, double, double, double);
extern void obpm_planewave(double, double, int);
extern void obpm_load(char, double, double, double, char, double);
extern void obpm_point(char, double, double, double, const char []);
extern void obpm_rfeed(double);
extern void obpm_pulsewidth(double);
extern void obpm_timestep(double);
extern void obpm_frequency1(double, double, int);
extern void obpm_frequency2(double, double, int);
extern void obpm_solver(int, int, double);
extern void obpm_pml(int, double, double);
extern void obpm_pbc(int, int, int);
extern void obpm_matchingloss(int);
extern void obpm_plotiter(int);
extern void obpm_plotfeed(int);
extern void obpm_plotpoint(int);
extern void obpm_plotsmith(int);
extern void obpm_plotzin(int, double, double, int);
extern void obpm_plotyin(int, double, double, int);
extern void obpm_plotref(int, double, double, int);
extern void obpm_plotspara(int, double, double, int);
extern void obpm_plotcoupling(int, double, double, int);
extern void obpm_plotfar0d(double, double, int, double, double, int);
extern void obpm_freqdiv(int);
extern void obpm_plotfar1d(char, int, double);
extern void obpm_far1dcomponent(int, int, int);
extern void obpm_far1dstyle(int);
extern void obpm_far1ddb(int);
extern void obpm_far1dnorm(int);
extern void obpm_far1dscale(double, double, int);
extern void obpm_plotfar2d(int, int);
extern void obpm_far2dcomponent(int, int, int, int, int, int, int);
extern void obpm_far2ddb(int);
extern void obpm_far2dscale(double, double);
extern void obpm_far2dobj(double);
extern void obpm_plotnear1d(const char [], char, double, double);
extern void obpm_near1ddb(int);
extern void obpm_near1dscale(double, double, int);
extern void obpm_near1dnoinc(int);
extern void obpm_plotnear2d(const char [], char, double);
extern void obpm_near2ddim(int, int);
extern void obpm_near2dframe(int);
extern void obpm_near2ddb(int);
extern void obpm_near2dscale(double, double);
extern void obpm_near2dcontour(int);
extern void obpm_near2dobj(int);
extern void obpm_near2dnoinc(int);
extern void obpm_near2dzoom(double, double, double, double);
extern void obpm_outdata(const char []);

// nearest integer
#define NINT(l, d) (int)((fabs(l) / fabs(d)) + 0.5)
#endif  // _OBPM_DATALIB_H_
